# Generated by Django 4.2.6 on 2023-11-15 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("secapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="recipe",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
