# Generated by Django 4.2.7 on 2023-11-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secapp", "0004_alter_recipe_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
